# Generated by Django 5.2.4 on 2025-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
